### PR TITLE
Added capability to load yaml files using loader

### PR DESCRIPTION
**Pull request by om-sharma**

### CODE REVIEW

**Comment by philandstuff** [comment]
can you give an example of usage? is this one-yaml-file-per-entry or one-big-yaml-file?

**Comment by om-sharma** [comment]
Command `./gradlew bulkLoad -PmintUrl=<minturl> -Pdatafile=<yaml file> -Ptype=yaml` will load the contents of yaml file as a single entry.

**Comment by philandstuff** [comment]
can you at least update the README to describe the new feature?

It might be worth starting to document more about the behaviour of the respective jsonl, csv, tsv, and yaml modes. This is something that will be easier once we split the repo.

**Comment by om-sharma** [comment]
ohh!! sorry for not updating README file. I have updated it in the last commit. I did not write in details because I think this is specific documentation for loader module and now I am very keen to separate it from this repository.

**Pull request merged**
